swagger: "2.0"
info:
    title: Library Service
    description: Service for managing library operations
    version: ""
host: localhost:8000
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /books:
        get:
            tags:
                - books
            summary: list books
            description: Retrieve all books
            operationId: books#list
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/BookResponse'
            schemes:
                - http
        post:
            tags:
                - books
            summary: create books
            description: Create a new book
            operationId: books#create
            parameters:
                - name: CreateRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/BooksCreateRequestBody'
                    required:
                        - title
                        - author
            responses:
                "201":
                    description: Created response.
                    schema:
                        $ref: '#/definitions/BooksCreateResponseBody'
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/BooksCreateBadRequestResponseBody'
            schemes:
                - http
    /books/{id}:
        get:
            tags:
                - books
            summary: show books
            description: Retrieve a book by ID
            operationId: books#show
            parameters:
                - name: id
                  in: path
                  description: ID of the book
                  required: true
                  type: integer
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/BooksShowResponseBody'
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/BooksShowNotFoundResponseBody'
            schemes:
                - http
        put:
            tags:
                - books
            summary: update books
            description: Update an existing book
            operationId: books#update
            parameters:
                - name: id
                  in: path
                  description: ID of the book
                  required: true
                  type: integer
                - name: UpdateRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/BooksUpdateRequestBody'
                    required:
                        - title
                        - author
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/BooksUpdateResponseBody'
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/BooksUpdateBadRequestResponseBody'
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/BooksUpdateNotFoundResponseBody'
            schemes:
                - http
        delete:
            tags:
                - books
            summary: delete books
            description: Delete a book by ID
            operationId: books#delete
            parameters:
                - name: id
                  in: path
                  description: ID of the book
                  required: true
                  type: integer
            responses:
                "204":
                    description: No Content response.
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/BooksDeleteNotFoundResponseBody'
            schemes:
                - http
    /openapi.json:
        get:
            tags:
                - books
            summary: Download ./gen/http/openapi.json
            operationId: books#/openapi.json
            responses:
                "200":
                    description: File downloaded
                    schema:
                        type: file
            schemes:
                - http
definitions:
    BookResponse:
        title: BookResponse
        type: object
        properties:
            author:
                type: string
                description: Author of the book
                example: Fugiat iste dolor.
            cover:
                type: string
                description: Base64 of the Book cover image
                example: QmFzZTY0IG9mIHRoZSBCb29rIGNvdmVyIGltYWdl
            id:
                type: integer
                description: ID of the book
                example: 4751107892946203695
                format: int64
            published_at:
                type: string
                description: Published date of the book
                example: "2006-01-02T15:04:05Z"
                format: date-time
            title:
                type: string
                description: Title of the book
                example: Ratione laboriosam odit.
        description: book entity.
        example:
            author: Quam alias totam odit vel.
            cover: QmFzZTY0IG9mIHRoZSBCb29rIGNvdmVyIGltYWdl
            id: 5606775090930396098
            published_at: "2006-01-02T15:04:05Z"
            title: Deleniti sit libero quia delectus illum.
    BooksCreateBadRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: Invalid request (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    BooksCreateRequestBody:
        title: BooksCreateRequestBody
        type: object
        properties:
            author:
                type: string
                description: Author of the book
                example: Voluptatem velit.
            cover:
                type: string
                description: Base64 of the Book cover image
                example: QmFzZTY0IG9mIHRoZSBCb29rIGNvdmVyIGltYWdl
            published_at:
                type: string
                description: Published date of the book
                example: "2006-01-02T15:04:05Z"
                format: date-time
            title:
                type: string
                description: Title of the book
                example: Placeat facilis culpa sed in beatae.
        example:
            author: Fugiat vitae.
            cover: QmFzZTY0IG9mIHRoZSBCb29rIGNvdmVyIGltYWdl
            published_at: "2006-01-02T15:04:05Z"
            title: Consequatur dolorem dolores quos nulla placeat earum.
        required:
            - title
            - author
    BooksCreateResponseBody:
        title: BooksCreateResponseBody
        type: object
        properties:
            author:
                type: string
                description: Author of the book
                example: Est est provident dolorem omnis.
            cover:
                type: string
                description: Base64 of the Book cover image
                example: QmFzZTY0IG9mIHRoZSBCb29rIGNvdmVyIGltYWdl
            id:
                type: integer
                description: ID of the book
                example: 6419043439154916590
                format: int64
            published_at:
                type: string
                description: Published date of the book
                example: "2006-01-02T15:04:05Z"
                format: date-time
            title:
                type: string
                description: Title of the book
                example: Necessitatibus nostrum nihil eum velit dolorum ut.
        example:
            author: Iure placeat voluptatem laudantium est et ipsa.
            cover: QmFzZTY0IG9mIHRoZSBCb29rIGNvdmVyIGltYWdl
            id: 5690469263725943225
            published_at: "2006-01-02T15:04:05Z"
            title: Consequatur repudiandae minima et.
    BooksDeleteNotFoundResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: Book not found (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    BooksShowNotFoundResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: Book not found (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    BooksShowResponseBody:
        title: BooksShowResponseBody
        type: object
        properties:
            author:
                type: string
                description: Author of the book
                example: Quae voluptas esse ea id assumenda a.
            cover:
                type: string
                description: Base64 of the Book cover image
                example: QmFzZTY0IG9mIHRoZSBCb29rIGNvdmVyIGltYWdl
            id:
                type: integer
                description: ID of the book
                example: 3512889487376451495
                format: int64
            published_at:
                type: string
                description: Published date of the book
                example: "2006-01-02T15:04:05Z"
                format: date-time
            title:
                type: string
                description: Title of the book
                example: Ducimus sed illo sapiente.
        example:
            author: Quos maiores aut quasi repellendus.
            cover: QmFzZTY0IG9mIHRoZSBCb29rIGNvdmVyIGltYWdl
            id: 2507535267211056824
            published_at: "2006-01-02T15:04:05Z"
            title: Nisi culpa autem.
    BooksUpdateBadRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: Invalid request (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    BooksUpdateNotFoundResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: Book not found (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    BooksUpdateRequestBody:
        title: BooksUpdateRequestBody
        type: object
        properties:
            author:
                type: string
                description: Author of the book
                example: Dolorem voluptatem.
            cover:
                type: string
                description: Base64 of the Book cover image
                example: QmFzZTY0IG9mIHRoZSBCb29rIGNvdmVyIGltYWdl
            published_at:
                type: string
                description: Published date of the book
                example: "2006-01-02T15:04:05Z"
                format: date-time
            title:
                type: string
                description: Title of the book
                example: Non non.
        example:
            author: Minus adipisci consequuntur.
            cover: QmFzZTY0IG9mIHRoZSBCb29rIGNvdmVyIGltYWdl
            published_at: "2006-01-02T15:04:05Z"
            title: Ut in qui quidem ab est.
        required:
            - title
            - author
    BooksUpdateResponseBody:
        title: BooksUpdateResponseBody
        type: object
        properties:
            author:
                type: string
                description: Author of the book
                example: Sint nulla tempore consectetur ut.
            cover:
                type: string
                description: Base64 of the Book cover image
                example: QmFzZTY0IG9mIHRoZSBCb29rIGNvdmVyIGltYWdl
            id:
                type: integer
                description: ID of the book
                example: 1016666915469702664
                format: int64
            published_at:
                type: string
                description: Published date of the book
                example: "2006-01-02T15:04:05Z"
                format: date-time
            title:
                type: string
                description: Title of the book
                example: Neque qui quidem architecto eum veniam.
        example:
            author: Blanditiis eos fuga eveniet deserunt.
            cover: QmFzZTY0IG9mIHRoZSBCb29rIGNvdmVyIGltYWdl
            id: 4141406523557002359
            published_at: "2006-01-02T15:04:05Z"
            title: Consectetur dolorum sed voluptatum nihil repudiandae voluptas.
